import os
import random
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable


class PlainLSTM(nn.Module):
    """PlainLSTM """
    def __init__(self, vocab_size, emb_dim, hidden_dim, use_cuda=False):
        super(PlainLSTM, self).__init__()
        self.vocab_size = vocab_size
        self.emb_dim = emb_dim
        self.hidden_dim = hidden_dim
        self.use_cuda = use_cuda
        self.emb = nn.Embedding(vocab_size, emb_dim)
        self.lstm = nn.LSTM(emb_dim, hidden_dim, batch_first=True)
        self.lin = nn.Linear(hidden_dim, vocab_size)
        self.log_softmax = nn.LogSoftmax(dim=1)
        self.init_params()

    def forward(self, x):

        emb = self.emb(x)  # emb dim: (batch_size, seq_len, emb_dim)
        h0, c0 = self.init_hidden(x.size(0))

        # input to lstm dimensions: (batch, seq_len, input_size)
        output, (h, c) = self.lstm(emb, (h0, c0))    # output dim = (batch_size x seq_len, x hidden_dim)
        
        seq_len = output.size()[1]
        batch_size = output.size()[0]

        pred = self.log_softmax(self.lin(output.contiguous().view(-1, self.hidden_dim)))
        pred = pred.view(batch_size, seq_len, self.vocab_size)
        return pred

    def step(self, x, h, c):
        """
        Args:
            x: (batch_size,  1), sequence of tokens generated by lstm
            h: (1, batch_size, hidden_dim), lstm hidden state
            c: (1, batch_size, hidden_dim), lstm cell state
        """
        emb = self.emb(x)
        output, (h, c) = self.lstm(emb, (h, c))
        pred = F.softmax(self.lin(output.view(-1, self.hidden_dim)), dim=1)
        return pred, h, c


    def init_hidden(self, batch_size):

        h = Variable(torch.zeros((1, batch_size, self.hidden_dim)))
        c = Variable(torch.zeros((1, batch_size, self.hidden_dim)))
        if self.use_cuda:
            h, c = h.cuda(), c.cuda()
        return h, c
    
    def init_params(self):
        for param in self.parameters():
            param.data.uniform_(-0.05, 0.05)

    def sample(self, batch_size, seq_len, x=None):
        res = []
        flag = False # whether sample from zero
        if x is None:
            flag = True
        if flag:
            x = Variable(torch.zeros((batch_size, 1)).long())
        if self.use_cuda:
            x = x.cuda()
        h, c = self.init_hidden(batch_size)
        samples = []
        if flag:
            for i in range(seq_len):
                output, h, c = self.step(x, h, c)
                x = output.multinomial(1)
                samples.append(x)
        else:
            given_len = x.size(1)
            lis = x.chunk(x.size(1), dim=1)
            for i in range(given_len):
                output, h, c = self.step(lis[i], h, c)
                samples.append(lis[i])
            x = output.multinomial(1)
            for i in range(given_len, seq_len):
                samples.append(x)
                output, h, c = self.step(x, h, c)
                x = output.multinomial(1)
        output = torch.cat(samples, dim=1)
        return output


    def test_sample(self, batch_size, seq_len, vocab_size):

        big_list = []
        x = Variable(torch.zeros((batch_size, 1)).long())
        h, c = self.init_hidden(batch_size)

        for i in range(seq_len):
            output, h, c = self.step(x, h, c)
            g = Variable(torch.zeros(output.size()))
            # print(g.size())
            g.data[:,0] = 1 # R*pij
            # output.backward(g)
            big_list.append((output, g))

        

        for p, g in big_list:
            p.backward(g)
        return output
        